languageName: English
weight: 1
params:
  author:
    name: "Roland Huß"
    headline: "The Milkman of Human Kindness"
    image: "img/profile.jpg"
    links:
      - github: https://github.com/rhuss
      - linkedin: https://linkedin.com/in/ro14nd
      - mastodon: https://hachyderm.io/@ro14nd
      - bluesky: https://bsky.app/profile/ro14nd.bsky.social
