colorScheme: "indigo"
defaultAppearance: "light"
autoSwitchAppearance: true

logo: "img/profile.jpg"
disableTextInHeader: true

homepage:
  layout: "profile"
  showRecent: true
  showRecentItems: 10
  showMoreLink: true
  showMoreLinkDest: "/posts/"
  cardView: false

article:
  showReadingTime: true
  showWordCount: true
  showDate: true
  showDateUpdated: false
  showAuthor: false
  showBreadcrumbs: false
  showTableOfContents: true
  showRelatedContent: true
  relatedContentLimit: 3
  showComments: true

footer:
  showCopyright: true
  showThemeAttribution: false

list:
  showBreadcrumbs: false
  groupByYear: true
  showSummary: true

enableSearch: true
